FROM azul/zulu-openjdk-alpine:21-jre-headless

RUN apk update && apk add fuse && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app
COPY ./dhfs-package-downloaded/. .
WORKDIR /usr/src/app/native-libs
COPY ./dhfs-native-downloaded/. .
WORKDIR /usr/src/app/webui
COPY ./webui-dist-downloaded/. .

ENV dhfs_webui_root=/usr/src/app/webui

WORKDIR /usr/src/app
COPY ./dockerentry.sh .

RUN ["chmod", "+x", "./dockerentry.sh"]

CMD [ "./dockerentry.sh" ]