#!/usr/bin/env bash
set -e
set -u
set -o pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

# 💀
LATEST=$(curl "https://api.github.com/repos/usatiuk/dhfs/actions/runs?branch=main&status=completed&per_page=1" | tr -d "[:space:]" | sed -en "s/.*\[\{\"id\":([0-9]*).*/\1/p")

echo Latest: $LATEST

CUR=$(cat "$SCRIPT_DIR"/version)

echo Current: $CUR

if [[ $CUR -ge $LATEST ]]; then
    echo Already latest!
    exit 1
fi

echo Downloading...

cd "$SCRIPT_DIR"

rm "Run wrapper.tar.gz" || true
rm -rf "dhfs" || true

wget https://nightly.link/usatiuk/dhfs/actions/runs/$LATEST/Run%20wrapper.tar.gz

tar xvf "Run wrapper.tar.gz"

rm -rf "DHFS Package"
rm -rf "Webui"

mv dhfs/app/* .

rm -rf "dhfs"

chmod +x run
chmod +x stop
chmod +x update

echo "Update complete!"
