version: 2.1

jobs:
  build-dhfs:
    machine:
      image: ubuntu-2004:current

    environment:
      JVM_OPTS: -Xmx1G
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Install required packages
          command: sudo apt-get update && sudo apt-get install -y fuse openjdk-21-jdk maven # FIXME

      - run:
          name: Java version
          command: java -version

      - restore_cache:
          keys:
            - dhfs-mvn-dependencies-{{ checksum "server/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - dhfs-mvn-dependencies-

      - run:
          name: Build and test
          command: cd server && mvn --batch-mode --update-snapshots package verify

      - store_artifacts:
          path: server/target/quarkus-app
          destination: dhfs-package

      - store_artifacts:
          path: server/target/surefire-reports
          destination: surefire-reports

      - store_artifacts:
          path: server/target/failsafe-reports
          destination: failsafe-reports

      - save_cache:
          paths:
            - ~/.m2/repository
          key: dhfs-mvn-dependencies-{{ checksum "server/pom.xml" }}

  build-webui:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout

      - restore_cache:
          keys:
            - webui-dependencies-{{ checksum "webui/package.json" }}

      - run:
          name: Install node modules
          command: cd webui && npm i

      - save_cache:
          paths:
            - webui/node_modules
          key: webui-dependencies-{{ checksum "webui/package.json" }}

      - run:
          name: Build
          command: cd webui && npm run build

      - store_artifacts:
          path: webui/dist
          destination: webui-dist

workflows:
  build-publish:
    jobs:
      - build-dhfs
      - build-webui
