version: 2.1

jobs:
  build-dhfs:
    machine:
      image: ubuntu-2004:current

    environment:
      JVM_OPTS: -Xmx1G
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Install required packages
          command: sudo apt-get update && sudo apt-get install -y fuse openjdk-21-jdk maven # FIXME

      - run:
          name: Java version
          command: java -version

      - restore_cache:
          keys:
            - dhfs-mvn-dependencies-{{ checksum "server/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - dhfs-mvn-dependencies-

      - run:
          name: Build and test
          command: cd server && mvn --batch-mode --update-snapshots package verify

      - run:
          name: Archive everything
          command: |
            zip -r dhfs-package.zip server/target/quarkus-app
            zip -r surefire-reports.zip server/target/surefire-reports
            zip -r failsafe-reports.zip server/target/failsafe-reports

      - store_artifacts:
          path: dhfs-package.zip
          destination: dhfs-package

      - store_artifacts:
          path: surefire-reports.zip
          destination: surefire-reports

      - store_artifacts:
          path: failsafe-reports.zip
          destination: failsafe-reports

      - save_cache:
          paths:
            - ~/.m2/repository
          key: dhfs-mvn-dependencies-{{ checksum "server/pom.xml" }}

  build-webui:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout

      - restore_cache:
          keys:
            - webui-dependencies-{{ checksum "webui/package.json" }}

      - run:
          name: Install node modules
          command: cd webui && npm i

      - save_cache:
          paths:
            - webui/node_modules
          key: webui-dependencies-{{ checksum "webui/package.json" }}

      - run:
          name: Build
          command: cd webui && npm run build

      - run:
          name: Archive everything
          command: |
            zip -r webui-dist.zip webui/dist

      - store_artifacts:
          path: webui-dist.zip
          destination: webui-dist

  docker-build-publish:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run:
          name: Log in to docker hub
          command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

      - run:
          name: Install emulators
          command: docker run --privileged --rm tonistiigi/binfmt --install all

      - run:
          name: Create docker builder
          command: docker buildx create --use --driver=docker-container

      - run:
          name: Get artifacts # FIXME
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/usatiuk/dhfs/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:")
            # generate a heredoc in BASH_ENV
            # the '\<<' is a CircleCI escape
            echo "read -r -d '' STORED_ARTIFACTS \<< 'EOF_ARTIFACTS'" >> $BASH_ENV
            echo "$artifacts" >> $BASH_ENV
            echo "EOF_ARTIFACTS" >> $BASH_ENV
            echo "$STORED_ARTIFACTS"

      - run:
          name: Download artifacts and unpack
          command: |
            for X in $STORED_ARTIFACTS
            do
              wget "$X"?circle-token=$CIRCLE_API_TOKEN
            done

            for X in $.zip
            do
              unzip $X
            done

            ls -lavh

      - restore_cache:
          keys:
            - buildx-dhfs-circleci-

      - run:
          name: Build and push to docker hub
          command: |
            docker buildx build --progress=plain --push --platform linux/arm64,linux/amd64
              --tag stepanusatiuk/dhfs:$CIRCLE_BRANCH \
              --cache-to=type=local,mode=max,dest=/tmp/dockercache \
              --cache-from=type=local,src=/tmp/dockercache ./Dockerfile.ci

      - run:
          name: Prune cache
          command: docker buildx prune --keep-storage=4gb --verbose

      - save_cache:
          key: buildx-dhfs-circleci-{{ checksum "/tmp/dockercache/index.json" }}
          paths:
            - /tmp/dockercache
workflows:
  build-publish:
    jobs:
      - build-dhfs
      - build-webui
      - docker-build-publish:
          requires:
            - build-dhfs
            - build-webui
          filters:
            branches:
              only: main
