#ifndef __LauncherAppMainFrame__
#define __LauncherAppMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "GLauncherApp.h"

//// end generated include

#include "DhfsInstance.hpp"

/** Implementing MainFrame */
class LauncherAppMainFrame : public MainFrame {
protected:
    // Handlers for MainFrame events.
    void OnStartStopButtonClick(wxCommandEvent& event);

public:
    /** Constructor */
    LauncherAppMainFrame(wxWindow* parent);

    //// end generated class members

private:
    DhfsInstance _dhfsInstance;
};

#endif // __LauncherAppMainFrame__
