name: Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sudo for ACT
        run: apt-get update && apt-get install -y sudo
        if: env.ACT=='true'

      - name: Install fuse and maven
        run: sudo apt-get update && sudo apt-get install -y fuse libfuse-dev maven

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: maven

      - name: Build and test with Maven
        run: cd server && mvn --batch-mode --update-snapshots verify -Djunit.jupiter.execution.parallel.config.fixed.parallelism=1

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: server/target/quarkus-app

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Test logs
          path: server/target/*-reports
