name: Server

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-dhfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sudo for ACT
        run: apt-get update && apt-get install -y sudo
        if: env.ACT=='true'

      - name: Install fuse and maven
        run: sudo apt-get update && sudo apt-get install -y fuse

      - name: Download maven
        run: |
          cd "$HOME"
          wget -qO- https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz | tar xvz
          $HOME/apache-maven-3.9.9-bin/bin/mvn

      - name: Update path
        run: echo "$HOME"/apache-maven-3.9.9-bin/bin >> $GITHUB_PATH

      - name: Maven info
        run: |
          echo $GITHUB_PATH
          echo $PATH
          mvn -v

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: maven

      - name: Test with Maven
        run: cd dhfs-parent && mvn --batch-mode --update-snapshots package verify

      - name: Build with Maven
        run: cd dhfs-parent && mvn --batch-mode --update-snapshots package # -Dquarkus.log.category.\"com.usatiuk.dhfs\".min-level=DEBUG

      - uses: actions/upload-artifact@v3
        with:
          name: DHFS Server Package
          path: dhfs-parent/server/target/quarkus-app

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Test logs
          path: dhfs-parent/**/target/*-reports

  build-webui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "webui/package.json"

      - name: NPM Install
        run: cd webui && npm i

      - name: NPM Build
        run: cd webui && npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: Webui
          path: webui/dist

  publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    needs: [build-webui, build-dhfs]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: DHFS Server Package
          path: dhfs-package-downloaded

      - uses: actions/download-artifact@v3
        with:
          name: Webui
          path: webui-dist-downloaded

      - name: Show all the files
        run: find .

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: "v2.2.4"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ci
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  publish-run-wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    needs: [build-webui, build-dhfs]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: DHFS Server Package
          path: dhfs-package-downloaded

      - uses: actions/download-artifact@v3
        with:
          name: Webui
          path: webui-dist-downloaded

      - name: Show all the files
        run: find .

      - name: Make run wrapper dirs
        run: mkdir -p run-wrapper-out/dhfs/data && mkdir -p run-wrapper-out/dhfs/fuse && mkdir -p run-wrapper-out/dhfs/app

      - name: Copy DHFS
        run: cp -r ./dhfs-package-downloaded "run-wrapper-out/dhfs/app/DHFS Package"

      - name: Copy Webui
        run: cp -r ./webui-dist-downloaded "run-wrapper-out/dhfs/app/Webui"

      - name: Copy run wrapper
        run: cp -r ./run-wrapper/* "run-wrapper-out/dhfs/app/"

      - name: Add version to run wrapper
        run: echo $GITHUB_RUN_ID > "run-wrapper-out/dhfs/app/"version

      - name: Tar run wrapper
        run: tar -cvf ~/run-wrapper.tar.gz ./run-wrapper-out

      - uses: actions/upload-artifact@v3
        with:
          name: Run wrapper
          path: ~/run-wrapper.tar.gz
